### ISSUE TITLE
Diseñar mockup en figma vista del blog

### ISSUE THREAD

**Issue by Juliancho2** [Trycatch-tv/trycatch_factory_site#114]
- Recurso:https://trycatch.tv/posts/71-proyectos-para-practicar-python/

**Comment by ZaliWow** [comment]
hecho, pero necesito requerimientos de funcionalidad, seran muchas publicaciones? hay que generar una vista para que puedan hacer publicaciones nuevas? donde pueden consultar las diferentes publicaciones los usuarios dentro de la landing.
