### ISSUE TITLE
Bloque de servicios del sitio

### ISSUE THREAD

**Issue by judlup** [Trycatch-tv/trycatch_factory_site#3]
**No olvide revisar el mockup antes de hacer cualquier código**

![Image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/3951903/6b6e52be-f2d0-4e29-8cf6-9565125c1dd8)

**Comment by ZaliWow** [comment]
Señor Juan, me gustaría tomar esta tarea, además del link para poder acceder al mockup final, gracias.

**Comment by ramtako8922** [comment]
Buenas tardes Juli la va tomar Zali o yo puedo

**Comment by judlup** [comment]
Tomado por [ZaliWow](https://github.com/ZaliWow)
