### ISSUE TITLE
Ajustar orden de las secciones 

### ISSUE THREAD

**Issue by Juliancho2** [Trycatch-tv/trycatch_factory_site#34]
Se debe ordenar las secciones de la landing según el mockup:

Orden de las secciones:

1. Navbar
2.  Hero
3. Nuestros servicios.
4. Nuestro proceso.
5. Seccion de tecnologias.
6. Seccion de preguntas frecuentes.
7. Seccion de call to action.
8. Formulario de contacto.
9. Footer.

**Comment by Laguilavo10** [comment]
Hola me gustaria colaborar con este issue
