### ISSUE TITLE
Bloque nuestro proceso del sitio

### ISSUE THREAD

**Issue by judlup** [Trycatch-tv/trycatch_factory_site#4]
**No olvide revisar el mockup antes de hacer cualquier código**

![Image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/3951903/1edea431-f854-463b-8584-44a0ce924e14)

**Comment by ramtako8922** [comment]
Juli buenas tardes yi quiero ayudarte con este

**Comment by ramtako8922** [comment]
Juli lo unico que no agregue fue los objetos multimedia que  muestra el mockup ya que  no se si ustedes ya tengan unos listos
