### ISSUE TITLE
Maquetar Vista services

### ISSUE THREAD

**Issue by Juliancho2** [Trycatch-tv/trycatch_factory_site#50]
-Maquetar vista de services de acuedo al mockup en figma:
-Ruta de vista src/pages/services/[service].astro
![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/87348556/40f1006d-0566-4564-b7ee-c7d6bdeddb10)
Mockup figma:
![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/87348556/88112583-6d9d-479e-98ec-18ad71d6af6b)

**Comment by ZaliWow** [comment]
terminado en figma
