### ISSUE TITLE
Maquetar vista Contacto

### ISSUE THREAD

**Issue by Juliancho2** [Trycatch-tv/trycatch_factory_site#53]
-Maquetar la vista de contacto de acuerdo al mockup en el figma.
-Ruta de la vista src/pages/contacto.astro.
Mockup figma:
![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/87348556/c61b08ab-f240-47b3-a4dc-b5653029c807)

**Comment by ZaliWow** [comment]
terminado en figma

**Comment by Brave094** [comment]
.
