### ISSUE TITLE
Footer del sitio

### ISSUE THREAD

**Issue by judlup** [Trycatch-tv/trycatch_factory_site#9]
**No olvide revisar el mockup antes de hacer cualquier código**

![Image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/3951903/abd3be4a-f2b2-49f4-b491-ed95714edf9b)

**Comment by judlup** [comment]
Tarea que lleva Ángel

**Comment by Angelxd0714** [comment]
Ese footer es mio mio es solo mio

**Comment by Orliluq** [comment]
si es solo tuyo tuyo jajajaja
