### ISSUE TITLE
corregir el tamaño del section mobile en la seccion de servicios del home y borrar botones de navegacion

### ISSUE THREAD

**Issue by ZaliWow** [Trycatch-tv/trycatch_factory_site#99]
solo se debe modificar el section, no las cards; esto para que no se vea tanto espacio en blanco arriba y abajo además quitar/borrar los botones de navegacion de la parte inferior de la card
![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/95185505/325f48f6-114b-4914-8ba8-8a84bc7048eb)

**Comment by Brave094** [comment]
.
